services:
  manager-service:
    tty: true
    depends_on:
      mongo-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    build:
      context: ../
      dockerfile: docker/manager/Dockerfile

    ports:
      - "8080:8080"
    networks:
      - crackhash-net

  worker-service:
    tty: true
    build:
      context: ../
      dockerfile: docker/worker/Dockerfile
    expose:
      - "8080"
    depends_on:
      - manager-service
    networks:
      - crackhash-net
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - crackhash-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  mongo1:
    image: mongo:7
    container_name: mongo1
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
    networks:
      - crackhash-net
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - mongo2-data:/data/db
    networks:
      - crackhash-net

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - mongo3-data:/data/db
    networks:
      - crackhash-net

  mongo-init:
    image: mongo:7
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_started
      mongo3:
        condition: service_started
    networks:
      - crackhash-net
    volumes:
      - ./init-replset.js:/init-replset.js:ro
    command: >
      bash -c "sleep 5 && mongosh --host mongo1:27017 /init-replset.js"

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

networks:
  crackhash-net:
    driver: bridge